@startuml

hide circle
skinparam classattributeiconsize 0
skinparam classFontStyle bold

class Persona {
 - apeNom: string
 - nif: string
 + setPaqueteC ( nuevoC: PaqueteDeCanales ): PaqueteDeCanales
 + getPaqueteC (): PaqueteDeCanales
 + setConexion ( nuevaC: ConexionInternet ): ConexionInternet
 + getConexion (): ConexionInternet
}

class PaqueteDeCanales{
 - descuento: float
}

class ConexionInternet {
 - tipo: string
 - velocidadMB: int
}

class Canal {
 - nombre: string
}

class MiExcepcion{
 - fichero: string
 - función: string
 - mensaje: string
}

Persona --> "miConexion" ConexionInternet: Contrata >
Persona --> "miPaquete" PaqueteDeCanales: Contrata >
PaqueteDeCanales o-- "2" Canal
Canal ..> MiExcepcion
ConexionInternet ..> MiExcepcion
Persona ..> MiExcepcion
PaqueteDeCanales ..> MiExcepcion

@enduml